spring:
  application:
    name: orgcraft

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    hikari:
      auto-commit: false

  # Datasource
  sql:
    init:
      mode: always

  # Virtual Threads
  threads:
    virtual:
      enabled: true

orgcraft:
  spicedb:
    enabled: true
    endpoint: localhost:50051
    preshared-key: orgcraft-dev-key
    plaintext: true